/*
 * This source file was generated by the Gradle 'init' task
 */
package io.confluent.example.aws.lambda;

import java.util.Map;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHandlesRequest() {
        App classUnderTest = new App();
        assertNull(classUnderTest.handleRequest(Map.of("key", "value"), null), "app should have a request handler");
    }
}
