/*
 * This source file was generated by the Gradle 'init' task
 */
package io.confluent.example.aws.lambda;

import java.util.Map;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class App implements RequestHandler<Map<String, String>, Void> {

    @Override
    public Void handleRequest(Map<String, String> event, Context context) {
        if (context != null) {
            LambdaLogger logger = context.getLogger();
            logger.log("EVENT TYPE: " + event.getClass());
        } else {
            event.forEach((k, v) -> System.out.println(k+"="+v));
        }
        return null;
    }

    public static void main(String[] args) {
        new App().handleRequest(Map.of("key", "Lambda!"), null);
    }
}
